Projekt/Models/Consultant.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Projekt.Models
{
    /// <summary>
    /// Consultant User Model mit jeweiligen Validation Constraints, erbt von Account
    /// CodeOwner: Thomas Gerum
    /// </summary>
    public class Consultant : Account
    {

        /// <summary>
        /// Vorname des Steuerberaters
        /// CodeOwner: Thomas Gerum, Vlad Kovganko
        /// </summary>

        [Required(ErrorMessage = "Vorname darf nicht leer sein")]
        [StringLength(50, MinimumLength = 1,
            ErrorMessage = "Ungültige Länge")]
        public string Firstname { get; set; }

        /// <summary>
        /// Nachname des Steuerberaters
        /// CodeOwner: Thomas Gerum, Vlad Kovganko
        /// </summary>
        [Required(ErrorMessage = "Nachname darf nicht leer sein")]
        [StringLength(50, MinimumLength = 1,
            ErrorMessage = "Ungültige Länge")]
        public string Lastname { get; set; }

        /// <summary>
        /// Adresse des Steuerberaters
        /// CodeOwner: Thomas Gerum, Vlad Kovganko
        /// </summary>
        [Required(ErrorMessage = "Adresse darf nicht leer sein")]
        [StringLength(200, MinimumLength = 1,
           ErrorMessage = "Ungültige Länge")]
        public string Address { get; set; }

        /// <summary>
        /// E-Mail des Steuerberaters
        /// CodeOwner: Thomas Gerum, Vlad Kovganko
        /// </summary>
        [Required(ErrorMessage = "E-mail darf nicht leer sein")]
        [EmailAddress(ErrorMessage = "Inkorrekte E-Mail")]
        public string Email { get; set; }

        /// <summary>
        /// Link zum Profilbild des Steuerberaters
        /// CodeOwner: Thomas Gerum
        /// </summary>
        public string Pathtoimage { get; set; }
    }
}

Projekt/ViewModels/AllCustomersViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

using Projekt.Models;
using Projekt.Utilities;
using Projekt.Controllers;


namespace Projekt.ViewModels
{
    /// <summary>
    /// Die Klasse <c>AllCustomerViewModel</c> bildet ein Model für die AllCustomer View
    /// CodeOwner: Alexander Rioux
    /// </summary>
    public class AllCustomersViewModel : BasicViewModel
    {
        /// <summary>
        /// DB Steuerberater zu Kunden
        /// CodeOwner: Alexander Rioux
        /// </summary>
        public ConsultantToCustomer consultantToCustomer { get; set; }
        /// <summary>
        /// Liste an Steuerberatern
        /// CodeOwner: Alexander Rioux
        /// </summary>
        public List<Consultant> ConsultantList { get; set; }
        /// <summary>
        /// Steuerberater zu seinen Kunden
        /// CodeOwner: Alexander Rioux
        /// </summary>
        public List<ConsultantWithCustomerList> ConsultantWithCustomerLists { get; set; }
        /// <summary>
        /// Eigene Kunden des derzeit betrachteten Steuerberaters mit Einsichten
        /// CodeOwner: Alexander Rioux
        /// </summary>
        public List<CustomerWithInsightstatus> MyCustomerList { get; set; }
        /// <summary>
        /// nicht zugeordnete Kunden
        /// CodeOwner: Alexander Rioux
        /// </summary>
        public List<Customer> NoConsultant { get; set; }
    }
}

Projekt/ViewModels/InsightViewModel.cs
using Projekt.Models;
using Projekt.Container;
using Projekt.Utilities;
namespace Projekt.ViewModels
{
    /// <summary>
    /// Die Klasse <c>InsightViewModel</c> bildet ein Model für die Insight und ExtendedInsight View
    /// CodeOwner: Alexander Rioux
    /// </summary>
    public class InsightViewModel : BasicViewModel
    {
        /// <summary>
        /// alle Assets des betrachteten Kunden
        /// CodeOwner: Alexander Rioux
        /// </summary>
        public List<Asset> AssetList { get; set; }
    }
}

Projekt/ViewModels/OwnCustomersViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Projekt.Models;
using Projekt.Controllers;

using Projekt.Utilities;

namespace Projekt.ViewModels
{
    /// <summary>
    /// Die Klasse <c>OwnCustomerViewModel</c> bildet ein Model für die OwnCustomer View
    /// CodeOwner: Alexander Rioux
    /// </summary>
    public class OwnCustomersViewModel : BasicViewModel
    {
        /// <summary>
        /// Liste der Kunden mit Einsichten
        /// CodeOwner: Alexander Rioux
        /// </summary>
        public List<CustomerWithInsightstatus> CustomerList { get; set; }
    }
}

Projekt/Controllers/ConsultantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Projekt.Models;
using Microsoft.AspNetCore.Authorization;
using Projekt.Utilities;
using Projekt.ViewModels;
using Projekt.Container;
using Microsoft.AspNetCore.Hosting;

namespace Projekt.Controllers
{
    /// <summary>
    /// Die Klasse <c>ConsultantController</c> regelt die Backend Aufgaben des Steuerberaters 
    /// Nutzer: Steuerberater
    /// CodeOwner: Thomas Gerum, Alexander Rioux, Christopher Glöckel
    /// </summary>
    [Authorize(Roles = "ConsultantRole")]
    public class ConsultantController : Controller
    {
        private readonly MvcAccountContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        TransactionContainer cont;
        /// <summary>
        /// Konstruktor
        /// </summary>
        public ConsultantController(MvcAccountContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            cont = new TransactionContainer(context);
            _webHostEnvironment = webHostEnvironment;
        }
        /// <summary>
        /// Initalisiert das <c>OwnCustomerViewModel</c> welches für die <c>OwnCustomers</c> View benötigt wird
        /// Nutzer: Steuerberater
        /// CodeOwner: Alexander Rioux, Christopher Glöckel
        /// </summary>
        /// <returns> OwnCustomers View </returns>
        public async Task<IActionResult> OwnCustomers()
        {
            string name = HttpContext.User.Identity.Name;
            OwnCustomersViewModel ownCustomersViewModel = new OwnCustomersViewModel();
            ownCustomersViewModel._Consultant = await _context.Consultant.FirstOrDefaultAsync(x => x.Username.ToLower() == name);
            ownCustomersViewModel.CustomerList = new List<CustomerWithInsightstatus>();
            List<ConsultantToCustomer> consultantToCustomer = _context.ConsultantToCustomer.Where(m => m.IdConsultant == ownCustomersViewModel._Consultant.Id).ToList();
            foreach (var selected in consultantToCustomer)
            {
                ownCustomersViewModel.CustomerList.Add(new CustomerWithInsightstatus()
                {
                    customer = await _context.Customer.FirstOrDefaultAsync(x => x.Id == selected.IdCustomer),
                    insightSimple = getInsight(ownCustomersViewModel._Consultant.Id, selected.IdCustomer),
                    insightExtended = getExtendedInsight(ownCustomersViewModel._Consultant.Id, selected.IdCustomer),
                    insightSimpleString = getInsightString(ownCustomersViewModel._Consultant.Id, selected.IdCustomer),
                    insightExtendedString = getExtendedInsightString(ownCustomersViewModel._Consultant.Id, selected.IdCustomer)
                });
            }
            return View(ownCustomersViewModel);
        }


        /// <summary>
        /// Initalisiert das <c>AllCustomersViewModel</c> welches für die <c>AllCustomers</c> View benötigt wird
        /// Nutzer: Steuerberater
        /// CodeOwner: Alexander Rioux
        /// </summary>
        /// <returns> AllCustomers View </returns>
        public async Task<IActionResult> AllCustomers()
        {
            int i = 0;
            string name = HttpContext.User.Identity.Name;
            AllCustomersViewModel allCustomersViewModel = new AllCustomersViewModel();
            allCustomersViewModel._Consultant = await _context.Consultant.FirstOrDefaultAsync(x => x.Username.ToLower() == name);
            if (allCustomersViewModel._Consultant == null)
            {
                return NotFound();
            }
            // Initialisierung
            allCustomersViewModel.ConsultantList = _context.Consultant.ToList();
            List<ConsultantToCustomer> consultantToCustomer = _context.ConsultantToCustomer.ToList();
            List<Customer> foundCustomer = new List<Customer>();
            allCustomersViewModel.MyCustomerList = new List<CustomerWithInsightstatus>() { };
            allCustomersViewModel.NoConsultant = new List<Customer>() { };
            allCustomersViewModel.ConsultantWithCustomerLists = new List<ConsultantWithCustomerList>() { };
            //Geht alle Customer durch um deren Kunden zu finden 
            foreach (var consultant in allCustomersViewModel.ConsultantList)
            {
                // Temporäre Objekte zur ermittlung der einzelnen Kunden
                IEnumerable<ConsultantToCustomer> temporaryConsultantToCustomer = consultantToCustomer.Where(m => m.IdConsultant == consultant.Id);
                List<Customer> temporaryCustomerList = new List<Customer>();
                ConsultantWithCustomerList temporaryConsultantWithCustomerList = new ConsultantWithCustomerList();
                temporaryConsultantWithCustomerList.Consultant = consultant;
                // Pro Steuerberater eigene Kunden finden
                foreach (var selected in temporaryConsultantToCustomer)
                {
                    temporaryCustomerList.Add(await _context.Customer.FirstOrDefaultAsync(x => x.Id == selected.IdCustomer));
                    foundCustomer.Add(await _context.Customer.FirstOrDefaultAsync(x => x.Id == selected.IdCustomer));
                }
                // Hinzufügen ins Model
                temporaryConsultantWithCustomerList.Customers = temporaryCustomerList;
                allCustomersViewModel.ConsultantWithCustomerLists.Add(temporaryConsultantWithCustomerList);
                i++;

            }
            //eigene Kunden ermitteln
            IEnumerable<ConsultantToCustomer> temporary2ConsultantToCustomer = consultantToCustomer.Where(m => m.IdConsultant == allCustomersViewModel._Consultant.Id);
            foreach (var selected in temporary2ConsultantToCustomer)
            {
                allCustomersViewModel.MyCustomerList.Add(new CustomerWithInsightstatus()
                {
                    customer = await _context.Customer.FirstOrDefaultAsync(x => x.Id == selected.IdCustomer),
                    insightSimple = getInsight(allCustomersViewModel._Consultant.Id, selected.IdCustomer),
                    insightExtended = getExtendedInsight(allCustomersViewModel._Consultant.Id, selected.IdCustomer),
                    insightSimpleString = getInsightString(allCustomersViewModel._Consultant.Id, selected.IdCustomer),
                    insightExtendedString = getExtendedInsightString(allCustomersViewModel._Consultant.Id, selected.IdCustomer)
                });
            }

            // Noch nicht zugeordnete Kunden finden
            foreach (var item in _context.Customer.ToList())
            {
                if (foundCustomer.FirstOrDefault(m => m.Id == item.Id) == null)
                    allCustomersViewModel.NoConsultant.Add(item);
            }
            return View(allCustomersViewModel);
        }

        /// <summary>
        /// Zeigt die Profilseite des jeweiligen Steuerberaters an
        /// CodeOwner: Vladyslav Kovganko
        /// </summary>
        /// <returns> Profile View</returns>
        [HttpGet]
        public async Task<IActionResult> Profile()
        {
            /*WICHTIG 

            Eingeloggter User für Navbar Layout eingeloggte User mitgegeben werden!!!!!
            Bei Fragen an Thomas wenden

            WICHTIG*/
            string name = HttpContext.User.Identity.Name;
            BasicViewModel data = new BasicViewModel();
            data._Consultant = await _context.Consultant.FirstOrDefaultAsync(x => x.Username.ToLower() == name);
            return View(data);
        }


        /// <summary>
        /// Validiert und setzt ggf. die Profildaten auf neue Werte. 
        /// CodeOwner: Vladyslav Kovganko
        /// </summary>
        /// <param name="form_data">Die vom User übergebene neuen Profildaten </param>
        /// <returns> Profil View mit neuen Werten falls die Validierung erfolgreich war, sonst alte Werte</returns>
        [HttpPost]
        public async Task<IActionResult> Profile(BasicViewModel form_data)
        {
            if (ModelState.IsValid)
            {
                _context.updateConsultantData(form_data._Consultant);
            }
            else
            {
                // Um in der Navbar den korrekten Namen anzuzeigen.
                string current_username = User.Identity.Name;
                Consultant? correct_user = await _context.Consultant.FirstOrDefaultAsync(u => u.Username == current_username);
                ViewData["error-case-name"] = correct_user.Firstname;
                ViewData["error-case-surname"] = correct_user.Lastname;
                ViewData["error-case-pathToProfileImg"] = correct_user.Pathtoimage;
                return View(form_data);
            }
            return RedirectToAction("Profile");
        }

        /// <summary>
        /// Aktualisiert das Profilbild des Nutzers
        /// CodeOwner: Vladyslav Kovganko
        /// </summary>
        /// <param name="imageFile">Die vom User übergebene Bilddatei</param>
        /// <returns> Profil View mit neuem Profilbild falls die Validierung erfolgreich war, sonst eine Fehlermeldung</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UploadProfileImg(IFormFile imageFile)
        {
            if (imageFile != null && isValidImage(imageFile))
            {
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "img/profile_img");
                string uniqueFileName = Guid.NewGuid().ToString() + "_" + imageFile.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                string relativeFilePath = "~" + filePath.Replace(_webHostEnvironment.WebRootPath, string.Empty)
                                                      .Replace("\\", "/");

Projekt/Views/Consultant/Create.cshtml
<!-- Create Consultant User View
Codeowner: Thomas Gerum -->

@model Projekt.Models.Consultant

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Steuerberater</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Firstname" class="control-label"></label>
                <input asp-for="Firstname" class="form-control" />
                <span asp-validation-for="Firstname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lastname" class="control-label"></label>
                <input asp-for="Lastname" class="form-control" />
                <span asp-validation-for="Lastname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Account" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Projekt/Views/Consultant/Delete.cshtml
<!-- Create Consultant User View
Codeowner: Thomas Gerum -->

@model Projekt.Models.Consultant

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Steuerberater</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Firstname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Firstname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lastname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lastname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pathtoimage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pathtoimage)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-controller="Account" asp-action="Index">Back to List</a>
    </form>
</div>

Projekt/Views/Consultant/Details.cshtml
<!-- Details Consultant User View
Codeowner: Thomas Gerum -->

@model Projekt.Models.Consultant

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Steuerberater</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Firstname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Firstname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lastname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lastname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pathtoimage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pathtoimage)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-controller="Account" asp-action="Index">Back to List</a>
</div>

Projekt/Views/Consultant/ExtendedInsight.cshtml
@model Projekt.ViewModels.InsightViewModel;
@using Projekt.Utilities;
@{
    ViewData["Title"] = "Erweiterte Einsichtnahme";
}
<!--Übersicht über steuerelevanten Details und Transaktionen des Kunden. Wird ausschließlich vom Steuerberater genutzt. -->
<!--CodeOwner: Alexander Rioux (Teile von Vald)-->
<style>
    .icons {
        object-fit: contain;
        width: 25px;
        height: 25px;
        border-radius: 50%;
    }
</style>

<head>
    <link rel="stylesheet" href="~/css/Customer/taxReportChooseYear_styles.css">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.2.0/css/datepicker.min.css"
        rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.2.0/js/bootstrap-datepicker.min.js"></script>
</head>

<div class="container">
    <div class="main-body">
        <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            <img src="@Url.Content(@Model._Customer.Pathtoimage)" alt="profile img" width="140px" ,
                                height="140px">
                            <div class="mt-3">
                                <h4>@Model._Customer.Firstname @Model._Customer.Lastname</h4>
                                <p class="text-secondary mb-1">@Model._Customer.Email</p>
                                <p class="text-muted font-size-sm">@Model._Customer.Address</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--Von Vlad kopiert -->
            <div class="col-md-4 mb-3">
                <div class="container">
                    <div class="input-year border rounded">
                        <form method="post" asp-action="ExtendedInsightTaxReport" asp-controller="Consultant"
                            class="row needs-validation" novalidate>
                            <input type="hidden" name="cusId" value="@Model._Customer.Id">
                            <div class="col-12">
                                <label for="validationCustom01" class="form-label">Wählen Sie das betreffende Jahr
                                    aus:</label>
                                <input type="text" class="form-control" name="year" id="datepicker" placeholder="Jahr"
                                    value="2023" />
                            </div>
                            <div class="col-12 mt-2 text-right">
                                <button class="btn btn-primary" type="submit">Absenden</button>
                            </div>
                        </form>
                    </div>


                    <script>
                        $(document).ready(function () {
                            $("#datepicker").datepicker({
                                format: "yyyy",
                                viewMode: "years",
                                minViewMode: "years",
                                autoclose: true
                            });
                        })


                    </script>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="d-flex flex-column align-items-center text-center">
                    <h4>Assets mit ihren Transaktionen</h4>
                </div>
                <!--Übersicht über alle Assets mit ihren Transaktionen -->
                <div class="accordion" id="accordionAsset">
                    @foreach (var asset in Model.AssetList)
                    {
                        <div class="accordion-item">
                            <h2 class="accordion-header" id=@FormatName(@asset.Name).Insert(0,"heading")>
                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                    data-bs-target=@FormatName(@asset.Name).Insert(0, "#collapse") aria-expanded="true"
                                    aria-controls=@asset.Name.Insert(0, "collapse")>
                                    <img src=@asset.LinkToImage alt="" class="icons"> &nbsp;
                                    <strong>@asset.Name</strong> &nbsp; Menge: @String.Format("{0:#,##0.############}",
                                @asset.Quantity) &nbsp; Wert:
                                    @String.Format("{0:#,##0.00######}", @asset.TotalValue) €
                                </button>
                            </h2>
                            <div id=@FormatName(@asset.Name).Insert(0, "collapse") class="accordion-collapse collapse"
                                aria-labelledby=@FormatName(@asset.Name).Insert(0, "heading")
                                data-bs-parent=@FormatName(@asset.Name).Insert(0, "#")>
                                <div class="accordion-body">
                                    <div class="table-responsive">
                                        <table class="table table-striped">
                                            <thead>
                                                <tr>
                                                    <th>Art</th>
                                                    <th>Kurs</th>
                                                    <th>Menge</th>
                                                    <th>Gebühr</th>
                                                    <th>Datum</th>
                                                    <th>Gesamtwert</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (Transaction transaktion in asset.Transactions)
                                                {
                                                    <tr>
                                                        <td>@transaktion.Type</td>
                                                        <td>@String.Format("{0:#,##0.00######}", @transaktion.Rate) €</td>
                                                        <td>@transaktion.Amount</td>
                                                        <td>@String.Format("{0:#,##0.00######}", @transaktion.Fee) €</td>
                                                        <td>@transaktion.PurchaseDate.ToString("dd.MM.yyyy")</td>
                                                        <td>@String.Format("{0:#,##0.00######}", @transaktion.Value) €</td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
@functions
{
    string FormatName(string name)
    {
        if (name.Contains("."))
        {
            name = name.Replace(".", "--");
        }
        return name;
    }
}

Projekt/Views/Consultant/Insight.cshtml
@model Projekt.ViewModels.InsightViewModel;
@using Projekt.Utilities;
@{
    ViewData["Title"] = "Erweiterte Einsichtnahme";
}
<!--Übersicht über steuerelevanten Details des Kunden. Wird ausschließlich vom Steuerberater genutzt. -->
<!--CodeOwner: Alexander Rioux-->

<head>
    <link rel="stylesheet" href="~/css/Customer/taxReportChooseYear_styles.css">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.2.0/css/datepicker.min.css"
        rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.2.0/js/bootstrap-datepicker.min.js"></script>
</head>
<style>
    .icons {
        object-fit: contain;
        width: 25px;
        height: 25px;
        border-radius: 50%;
    }
</style>

<head>
    <link rel="stylesheet" href="~/css/Customer/taxReport_styles.css">
</head>
<div class="container">
    <div class="main-body">
        <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            <img src="@Url.Content(@Model._Customer.Pathtoimage)" alt="profile img" width="140px" ,
                                height="140px">
                            <div class="mt-3">
                                <h4>@Model._Customer.Firstname @Model._Customer.Lastname</h4>
                                <p class="text-secondary mb-1">@Model._Customer.Email</p>
                                <p class="text-muted font-size-sm">@Model._Customer.Address</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--Von Vlad kopiert -->
            <div class="col-md-4 mb-3">
                <div class="container">
                    <div class="input-year border rounded">
                        <form method="post" asp-action="InsightTaxReport" asp-controller="Consultant"
                            class="row needs-validation" novalidate>
                            <input type="hidden" name="cusId" value="@Model._Customer.Id">
                            <div class="col-12">
                                <label for="validationCustom01" class="form-label">Wählen Sie das betreffende Jahr
                                    aus:</label>
                                <input type="text" class="form-control" name="year" id="datepicker" placeholder="Jahr"
                                    value="2023" />
                            </div>
                            <div class="col-12 mt-2 text-right">
                                <button class="btn btn-primary" type="submit">Absenden</button>
                            </div>
                        </form>
                    </div>


                    <script>
                        $(document).ready(function () {
                            $("#datepicker").datepicker({
                                format: "yyyy",
                                viewMode: "years",
                                minViewMode: "years",
                                autoclose: true
                            });
                        })


                    </script>
                </div>
            </div>

        </div>
    </div>
</div>