Abgaben/Uebungsblatt6/Einzelabgaben/Kovganko/SoPro23Team08/Models/ErrorViewModel.cs
namespace SoPro23Team08.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Abgaben/Uebungsblatt6/Einzelabgaben/Kovganko/SoPro23Team08/Models/Lesson.cs
using System.ComponentModel.DataAnnotations;

namespace SoPro23Team08.Models
{
    public class Lesson
    {
       // [Display(Name = "Id")]
       // [Required(ErrorMessage = "Geben Sie eine Id ein")]
       // [Range(uint.MinValue, uint.MaxValue, ErrorMessage = "Eine Id darf nicht negativ sein")]
        public int Id { get; set; }

        [Required(ErrorMessage = "Geben Sie einen Titel ein")]
        [MinLength(1, ErrorMessage = "Geben Sie einen Titel ein")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Geben Sie einen gültigen Link ein")]
        [Url]
        public string url { get; set; }
 
        [Required(ErrorMessage = "Geben Sie einen Aufwand ein")]
        [Range(0, double.MaxValue, ErrorMessage = "Ein Aufwand darf nicht negativ sein")]
        public double? estimate { get; set; }

      /*  public Lesson(string Title, string CardDeckLink, int TimeEstimation){
            this.Id = nextId++;
            this.Title = Title;
            this.CardDeckLink = CardDeckLink;
            this.TimeEstimation = TimeEstimation;
        }*/

        public string toString()
        {
            return Id + " " + Title + " " + url + " " + estimate;
        }
    }
}

Abgaben/Uebungsblatt6/Einzelabgaben/Kovganko/SoPro23Team08/Models/LessonContainer.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using SoPro23Team08.Data;
using System.Reflection.Metadata;

namespace SoPro23Team08.Models
{
    public class LessonContainer
    {
        private static LessonContext db = new LessonContext();   
        public List<Lesson> getLessons()
        {
            return db.Lessons.ToList(); 
        }

        public void addLesson(Lesson lesson) {
            db.Add(lesson);
            db.SaveChanges();
            Console.WriteLine("New lesson with id " + lesson.Id + " inserted");
        }

        public void RemoveLesson(int id)
        {
            Lesson? lToRemove = db.Find<Lesson>(id);
            if(lToRemove != null) { 
                db.Remove(lToRemove);      
            }
            db.SaveChanges();
            Console.WriteLine("Lesson with id " + id + " removed");
            Lesson? idOne = db.Find<Lesson>(1);
        }

        public void UpdateLesson(Lesson lesson)
        {
            if(lesson != null)
            {
                db.ChangeTracker.Clear();
                db.Update(lesson);    
                db.SaveChanges();
                Console.WriteLine("Lesson with id " + lesson.Id + " updated");
            }
        }

        public Lesson? getLesson(int id) {
            return db.Find<Lesson>(id);
        }

        public Boolean containsLesson(int id) { 
            return db.Find<Lesson>(id) == null ? false : true;   
        }
    }
}

Abgaben/Uebungsblatt6/Einzelabgaben/Kovganko/SoPro23Team08/ViewModels/LessonViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SoPro23Team08.Models;

namespace SoPro23Team08.ViewModels
{
    public class LessonViewModel
    {
        
    }
}

Abgaben/Uebungsblatt6/Einzelabgaben/Kovganko/SoPro23Team08/ViewModels/TeachingplanViewModel.cs
using SoPro23Team08.Models;

namespace SoPro23Team08.ViewModels
{
    public class TeachingplanViewModel
    {
        public static LessonContainer lessonContainer = new LessonContainer(); 

        public static void lessonInsertOrUpdateIfExist(Lesson[] lessons)
        {
            foreach(Lesson l in lessons){
                if(lessonContainer.containsLesson(l.Id)) { 
                    lessonContainer.UpdateLesson(l);
                }
                else
                {
                    lessonContainer.addLesson(l);
                }
            }
        }
    }

   
}

Abgaben/Uebungsblatt6/Einzelabgaben/Kovganko/SoPro23Team08/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SoPro23Team08.Models;

namespace SoPro23Team08.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Abgaben/Uebungsblatt6/Einzelabgaben/Kovganko/SoPro23Team08/Controllers/TeachingplanController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SoPro23Team08.Models;
using SoPro23Team08.ViewModels;

namespace SoPro23Team08.Controllers
{
    public class TeachingplanController : Controller
    {
       
        public IActionResult Index()
        {
            return View(TeachingplanViewModel.lessonContainer.getLessons());
        }

        public IActionResult CreateLesson()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateLesson(Lesson lesson)
        {
           if(lesson != null)
            {
                if (ModelState.IsValid)
                {
                    TeachingplanViewModel.lessonContainer.addLesson(lesson);    
                    return RedirectToAction("Index");
                }
            }
            return View(lesson);
        }

        public IActionResult RemoveLesson(int lessonId){
            TeachingplanViewModel.lessonContainer.RemoveLesson(lessonId);  
         
           return RedirectToAction("Index");
        }

        public IActionResult EditLesson(int lessonId)
        {
            var lessonToEdit = TeachingplanViewModel.lessonContainer.getLesson(lessonId);   

            if(lessonToEdit == null)
            {
                return NotFound();
            }
            return View("EditLesson", lessonToEdit);
        }

        [HttpPost]
        public IActionResult EditLesson(Lesson lesson)
        {
            if (!ModelState.IsValid)
            {
                return View(lesson);
            }


            if(lesson != null)
            {
                TeachingplanViewModel.lessonContainer.UpdateLesson(lesson);
            }
          
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UploadJson(IFormFile jsonFile)
        {
            if(jsonFile != null && jsonFile.Length > 0 && jsonFile.ContentType == "application/json")
            {
                using(var streamReader = new StreamReader(jsonFile.OpenReadStream()))
                {
                    var jsonString = streamReader.ReadToEnd();
                    Lesson[]? lessons = JsonConvert.DeserializeObject<Lesson[]>(jsonString);
                    TeachingplanViewModel.lessonInsertOrUpdateIfExist(lessons); 
                    
                }
            }
            return RedirectToAction("Index");
        }

    } 
}

Abgaben/Uebungsblatt6/Einzelabgaben/Kovganko/SoPro23Team08/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SoPro23Team08</title>
  <!--   <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />-->



    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>


    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SoPro23Team08.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SoPro23Team08</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Studium</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teachingplan" asp-action="Index">Lehrplan</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container p-0">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SoPro23Team08 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Abgaben/Uebungsblatt6/Einzelabgaben/Kovganko/SoPro23Team08/Views/Teachingplan/CreateLesson.cshtml
@model Lesson


<style>
    .input-validation-error{

    }
</style>

<h1>Lektion hinzufügen</h1>

<form asp-action="CreateLesson" method="post" class="input_data_form pl-3 pt-3" style="width: 500px">
   <!--<div class="form-group">
        <label asp-for="Id"></label>
        <span class="text-danger" asp-validation-for="Id"></span>
        <input asp-for="Id" type="text" class="form-control" placeholder="Id">
     </div> -->
    <div class="form-group">
        <label asp-for="Title">Titel</label>
        <span class="text-danger" asp-validation-for="Title"></span>
        <input asp-for="Title" type="text" class="form-control" placeholder="Titel">

    </div>
    <div class="form-group">
        <label asp-for="estimate">Geschätzte Kartendauer</label>
        <span class="text-danger" asp-validation-for="estimate"></span>
        <input asp-for="estimate" type="text" class="form-control" placeholder="Geschätzte Kartendauer">

    </div>
    <div class="form-group pb-2">
        <label asp-for="url">Externer Karten-Link</label>
        <span class="text-danger" asp-validation-for="url"></span>
        <input asp-for="url" type="url" class="form-control" placeholder="Link">

    </div>
    <button type="submit" class="btn btn-primary">Hinzufügen</button>
</form>

<h3>oder mit Hilfe einer JSON-Datei:</h3>

 <form asp-action="UploadJson" class="pl-3" method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label for="file">Wählen Sie eine JSON-Datei aus</label>
            <input name="jsonFile" type="file" class="form-control-file" id="file" name="file">
        </div>
        <button type="submit" class="btn btn-primary">Hochladen</button>
</form>

Abgaben/Uebungsblatt6/Einzelabgaben/Kovganko/SoPro23Team08/Views/Teachingplan/EditLesson.cshtml
@model Lesson



<h1>Lektion editieren</h1>

<form asp-action="EditLesson" method="post" class="pl-3 pt-3" style="width: 500px">
    <div class="form-group" hidden>
        <label asp-for="Id"></label>
        <input asp-for="Id" type="text" class="form-control" placeholder="Id">
    </div>
    <div class="form-group">
        <label asp-for="Title">Titel</label>
        <span class="text-danger" asp-validation-for="Title"></span>
        <input asp-for="Title" type="text" class="form-control" placeholder="Titel">
    </div>
    <div class="form-group">
        <label asp-for="estimate">Geschätzte Kartendauer</label>
        <span class="text-danger" asp-validation-for="estimate"></span>
        <input asp-for="estimate" type="text" class="form-control" placeholder="Geschätzte Kartendauer">
    </div>
    <div class="form-group pb-2">
        <label asp-for="url">Externer Karten-Link</label>
        <span class="text-danger" asp-validation-for="url"></span>
        <input asp-for="url" type="text" class="form-control" placeholder="Link">
    </div>
    <button type="submit" class="btn btn-primary">Bestätigen</button>
</form>

Abgaben/Uebungsblatt6/Einzelabgaben/Kovganko/SoPro23Team08/Views/Teachingplan/Index.cshtml
@{
    ViewData["Title"] = "Lehrplan";
}


<h1>
    Aktuelle Lehrplanübersicht</h2>

 <div class="row mt-3">
    <div class="card ml-3 mb-3 text-center" style="width: 17rem">
        <div class="card-body">
          <h5 class="card-title p-2">
            Neue Lektion hinzufügen
          </h5>
          <a class="btn add-btn btn-primary btn-lg" asp-action="CreateLesson">+</a>
        </div>
      </div>
     @for(int i = 0; i < @Model.Count; i++)
     {
         var lesson = @Model[i];
         <div class="card ml-3 mb-3" style="width: 17rem">
             <div class="card-body">
                 <h5 class="card-title">[@lesson.Id] @lesson.Title</h5>
                 <div class="card-content">
                   <a href="@lesson.url" class="card-link">Externer Karten-Link</a>
                   <p class="card-text">Geschätzte Kartendauer:
                     <span class="badge badge-primary">@lesson.estimate Tage</span>
                   </p>
                    <div class="card-buttons">
                            <a class="btn btn-primary" asp-controller="Teachingplan" asp-action="EditLesson" asp-route-lessonId="@lesson.Id">Bearbeiten</a>
                        <a class="btn btn-danger" asp-controller="Teachingplan" asp-action="RemoveLesson" asp-route-lessonId="@lesson.Id">Löschen</a>
                    </div>
                 </div>
             </div>
         </div>
     }
 </div> 



 